name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-ubuntu:
    name: Build & Test on Ubuntu 22.04 (CPU only)
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ ninja-build

      - name: Configure and build
        run: |
          cmake . -B build -G Ninja \
            -D CMAKE_BUILD_TYPE=Release \
            -D VISP_CI=ON \
            -D VISP_FMT_LIB=ON
          cmake --build build

      - name: Run tests
        run: ctest build

  build-test-ubuntu-vulkan:
    name: Build & Test on Ubuntu 22.04 with Vulkan
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list https://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list
          sudo apt-get update -y
          sudo apt-get install -y build-essential cmake g++ ninja-build mesa-vulkan-drivers vulkan-sdk

      - name: Configure and build with Vulkan
        run: |
          cmake . -B build -G Ninja \
            -D CMAKE_BUILD_TYPE=Release \
            -D VISP_CI=ON \
            -D VISP_VULKAN=ON \
            -D VISP_FMT_LIB=ON
          cmake --build build

      - name: Run tests
        run: ctest build

  build-test-windows:
    name: Build & Test on Windows (CPU only)
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v2

      - name: Configure
        run: >
          cmake . -B build -G Ninja -A x64
            -D CMAKE_BUILD_TYPE=Release
            -D VISP_CI=ON

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: ctest build

  build-test-macos:
    name: Build & Test on macOS (CPU only)
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: brew install cmake

      - name: Configure and build
        run: |
          cmake -G Ninja . -B build \
            -D CMAKE_BUILD_TYPE=Release \
            -D VISP_CI=ON \
            -D GGML_METAL=OFF \
            -D GGML_RPC=ON \
            -D CMAKE_BUILD_RPATH="@loader_path"
          cmake --build build

      - name: Run tests
        run: ctest build
